/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.proyecto1dam.vista;

import java.awt.Color;

/**
 *
 * @author andres
 */
public class AdministradoresBuscar extends javax.swing.JPanel {

    /**
     * Creates new form ProfesoresForm
     */
    public AdministradoresBuscar() {
        initComponents();
        
        panelInferiorProfes.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        profeLabel = new javax.swing.JLabel();
        buscarPanel = new javax.swing.JPanel();
        buscarLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        panelInferiorProfes = new javax.swing.JPanel();
        botoneraProfesPanel = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        masOpcionesLabel = new javax.swing.JLabel();

        setBackground(new Color (0,0,0,0));
        setMinimumSize(new java.awt.Dimension(800, 450));
        setPreferredSize(new java.awt.Dimension(800, 450));
        setLayout(null);

        profeLabel.setFont(new java.awt.Font("Ubuntu Light", 3, 24)); // NOI18N
        profeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profeLabel.setText("GRUPOS");
        add(profeLabel);
        profeLabel.setBounds(0, 0, 800, 50);

        buscarPanel.setLayout(null);

        buscarLabel.setText("Buscar Profesor...");
        buscarPanel.add(buscarLabel);
        buscarLabel.setBounds(23, 12, 88, 14);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Nombre");
        buscarPanel.add(jLabel1);
        jLabel1.setBounds(20, 50, 120, 20);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Apellido 1");
        buscarPanel.add(jLabel2);
        jLabel2.setBounds(20, 90, 120, 20);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Apellido 2");
        buscarPanel.add(jLabel3);
        jLabel3.setBounds(20, 130, 120, 20);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("DNI");
        buscarPanel.add(jLabel4);
        jLabel4.setBounds(20, 170, 120, 20);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        buscarPanel.add(jTextField1);
        jTextField1.setBounds(162, 47, 150, 20);
        buscarPanel.add(jTextField2);
        jTextField2.setBounds(162, 87, 150, 20);
        buscarPanel.add(jTextField3);
        jTextField3.setBounds(162, 127, 150, 20);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        buscarPanel.add(jTextField4);
        jTextField4.setBounds(162, 167, 150, 20);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Localidad");
        buscarPanel.add(jLabel5);
        jLabel5.setBounds(350, 50, 120, 20);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Tel. Fijo");
        buscarPanel.add(jLabel6);
        jLabel6.setBounds(350, 90, 120, 20);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Tel. Móvil");
        buscarPanel.add(jLabel7);
        jLabel7.setBounds(350, 130, 120, 20);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("E-Mail");
        buscarPanel.add(jLabel8);
        jLabel8.setBounds(350, 170, 120, 20);
        buscarPanel.add(jTextField5);
        jTextField5.setBounds(494, 47, 150, 20);
        buscarPanel.add(jTextField6);
        jTextField6.setBounds(494, 87, 150, 20);
        buscarPanel.add(jTextField7);
        jTextField7.setBounds(494, 127, 150, 20);

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        buscarPanel.add(jTextField8);
        jTextField8.setBounds(494, 167, 150, 20);

        jButton1.setText("Buscar!");
        buscarPanel.add(jButton1);
        jButton1.setBounds(710, 120, 70, 70);

        add(buscarPanel);
        buscarPanel.setBounds(0, 50, 800, 200);
        add(jSeparator1);
        jSeparator1.setBounds(0, 280, 800, 2);

        panelInferiorProfes.setBackground(new Color(0,0,0,0));
        panelInferiorProfes.setOpaque(false);
        panelInferiorProfes.setLayout(null);

        botoneraProfesPanel.setLayout(null);

        jButton2.setText("<html><center>Añadir<br />Profesor</center></html>");
        botoneraProfesPanel.add(jButton2);
        jButton2.setBounds(0, 0, 90, 90);

        jButton3.setText("<html><center>Mostrar<br />todos</center></html>");
        botoneraProfesPanel.add(jButton3);
        jButton3.setBounds(90, 0, 90, 90);

        jButton4.setText("<html><center>Volver<br />al Menú</center></html>");
        botoneraProfesPanel.add(jButton4);
        jButton4.setBounds(180, 0, 90, 90);

        jButton5.setText("Ayuda");
        botoneraProfesPanel.add(jButton5);
        jButton5.setBounds(270, 0, 90, 90);

        jButton6.setText("Salir");
        botoneraProfesPanel.add(jButton6);
        jButton6.setBounds(510, 0, 90, 90);

        panelInferiorProfes.add(botoneraProfesPanel);
        botoneraProfesPanel.setBounds(100, 50, 600, 90);

        masOpcionesLabel.setText("Más Opciones...");
        panelInferiorProfes.add(masOpcionesLabel);
        masOpcionesLabel.setBounds(23, 12, 78, 14);

        add(panelInferiorProfes);
        panelInferiorProfes.setBounds(0, 290, 800, 160);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botoneraProfesPanel;
    private javax.swing.JLabel buscarLabel;
    private javax.swing.JPanel buscarPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel masOpcionesLabel;
    private javax.swing.JPanel panelInferiorProfes;
    private javax.swing.JLabel profeLabel;
    // End of variables declaration//GEN-END:variables
}
