/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.proyecto1dam.vista;

/**
 *
 * @author amacias
 */
public class DetallesProfesores extends javax.swing.JPanel {

    /**
     * Creates new form DetallesProfesores
     */
    public DetallesProfesores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        profeLabel1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();

        setLayout(null);

        profeLabel1.setFont(new java.awt.Font("Ubuntu Light", 3, 24)); // NOI18N
        profeLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profeLabel1.setText("PROFESORES");
        add(profeLabel1);
        profeLabel1.setBounds(300, 0, 200, 40);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Nombre");
        add(jLabel1);
        jLabel1.setBounds(50, 60, 120, 14);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Apellido 1");
        add(jLabel2);
        jLabel2.setBounds(50, 100, 120, 14);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Apellido 2");
        add(jLabel3);
        jLabel3.setBounds(50, 140, 120, 14);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Sexo");
        add(jLabel4);
        jLabel4.setBounds(50, 180, 120, 14);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Dirección");
        add(jLabel5);
        jLabel5.setBounds(50, 220, 120, 14);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Localidad");
        add(jLabel6);
        jLabel6.setBounds(50, 260, 120, 14);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Teléfono fijo");
        add(jLabel7);
        jLabel7.setBounds(50, 300, 120, 14);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Teléfono móvil");
        add(jLabel8);
        jLabel8.setBounds(50, 340, 120, 14);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("E-Mail");
        add(jLabel9);
        jLabel9.setBounds(50, 380, 120, 14);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Usuario");
        add(jLabel10);
        jLabel10.setBounds(400, 60, 145, 14);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Contraseña");
        add(jLabel11);
        jLabel11.setBounds(400, 100, 145, 14);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("DNI");
        add(jLabel12);
        jLabel12.setBounds(400, 140, 145, 14);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Nº Seguridad Social");
        add(jLabel13);
        jLabel13.setBounds(400, 180, 145, 14);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("CCC");
        add(jLabel14);
        jLabel14.setBounds(400, 220, 145, 14);

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Material");
        add(jLabel15);
        jLabel15.setBounds(400, 260, 145, 14);

        jButton1.setText("Guardar Profesor");
        add(jButton1);
        jButton1.setBounds(450, 310, 210, 23);

        jButton2.setText("Volver atrás");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(450, 360, 210, 23);
        add(jTextField1);
        jTextField1.setBounds(180, 55, 150, 30);
        add(jTextField2);
        jTextField2.setBounds(180, 95, 150, 30);
        add(jTextField3);
        jTextField3.setBounds(180, 135, 150, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Femenino" }));
        add(jComboBox1);
        jComboBox1.setBounds(180, 175, 150, 30);
        add(jTextField4);
        jTextField4.setBounds(180, 215, 150, 30);
        add(jTextField5);
        jTextField5.setBounds(180, 255, 150, 30);
        add(jTextField6);
        jTextField6.setBounds(180, 295, 150, 30);
        add(jTextField7);
        jTextField7.setBounds(180, 335, 150, 30);
        add(jTextField8);
        jTextField8.setBounds(180, 375, 150, 30);
        add(jTextField9);
        jTextField9.setBounds(560, 55, 150, 30);
        add(jTextField10);
        jTextField10.setBounds(560, 95, 150, 30);
        add(jTextField11);
        jTextField11.setBounds(560, 135, 150, 30);

        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        add(jTextField12);
        jTextField12.setBounds(560, 175, 150, 30);
        add(jTextField13);
        jTextField13.setBounds(560, 215, 150, 30);
        add(jTextField14);
        jTextField14.setBounds(560, 255, 150, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel profeLabel1;
    // End of variables declaration//GEN-END:variables
}
