/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.proyecto1dam.vista;

import com.proyecto1dam.controlador.CrudProfesor;
import com.proyecto1dam.modelo.Profesor;
import java.awt.Color;
import java.awt.Dimension;
import java.util.List;
import javax.swing.BorderFactory;

/**
 *
 * @author andres
 */
public class MarcoBase extends javax.swing.JFrame {

    /**
     * Creates new form ESAPrincipal
     */
    public MarcoBase() {
        initComponents();
        setLocationRelativeTo(null);
        getRootPane().setBorder(BorderFactory.createMatteBorder(4, 4, 4, 4, Color.BLACK));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoPanel = new javax.swing.JPanel();
        logoIMGPanel = new javax.swing.JPanel();
        imgLabel = new javax.swing.JLabel();
        nombrePanel = new javax.swing.JPanel();
        nombreESALabel = new javax.swing.JLabel();
        identificarPanel = new javax.swing.JPanel();
        identifLabel = new javax.swing.JLabel();
        usuarioLabel = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        topMenuPanel = new javax.swing.JPanel();
        alumnosTopButton = new javax.swing.JButton();
        profesoresTopButton = new javax.swing.JButton();
        gruposTopButton = new javax.swing.JButton();
        centrosTopButton = new javax.swing.JButton();
        administradoresTopButton = new javax.swing.JButton();
        ayudaTopButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);
        getContentPane().setLayout(null);

        logoPanel.setLayout(null);

        imgLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/logoESAb.png"))); // NOI18N

        javax.swing.GroupLayout logoIMGPanelLayout = new javax.swing.GroupLayout(logoIMGPanel);
        logoIMGPanel.setLayout(logoIMGPanelLayout);
        logoIMGPanelLayout.setHorizontalGroup(
            logoIMGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        logoIMGPanelLayout.setVerticalGroup(
            logoIMGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        logoPanel.add(logoIMGPanel);
        logoIMGPanel.setBounds(0, 0, 100, 100);

        nombrePanel.setPreferredSize(new java.awt.Dimension(100, 60));

        nombreESALabel.setFont(new java.awt.Font("DejaVu Serif", 3, 36)); // NOI18N
        nombreESALabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreESALabel.setText("Escuela Sevillana de Ajedrez");

        javax.swing.GroupLayout nombrePanelLayout = new javax.swing.GroupLayout(nombrePanel);
        nombrePanel.setLayout(nombrePanelLayout);
        nombrePanelLayout.setHorizontalGroup(
            nombrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nombrePanelLayout.createSequentialGroup()
                .addComponent(nombreESALabel, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        nombrePanelLayout.setVerticalGroup(
            nombrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nombreESALabel, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        logoPanel.add(nombrePanel);
        nombrePanel.setBounds(100, 0, 700, 60);

        identifLabel.setFont(new java.awt.Font("Droid Sans Fallback", 0, 12)); // NOI18N
        identifLabel.setText("Identificado como: ");

        usuarioLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usuarioLabel.setText("admin");

        logoutButton.setText("Salir");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout identificarPanelLayout = new javax.swing.GroupLayout(identificarPanel);
        identificarPanel.setLayout(identificarPanelLayout);
        identificarPanelLayout.setHorizontalGroup(
            identificarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(identificarPanelLayout.createSequentialGroup()
                .addContainerGap(152, Short.MAX_VALUE)
                .addComponent(identifLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(usuarioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoutButton)
                .addGap(87, 87, 87))
        );
        identificarPanelLayout.setVerticalGroup(
            identificarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(identificarPanelLayout.createSequentialGroup()
                .addGroup(identificarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(identifLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(usuarioLabel)
                    .addComponent(logoutButton))
                .addContainerGap())
        );

        logoPanel.add(identificarPanel);
        identificarPanel.setBounds(100, 60, 700, 40);

        getContentPane().add(logoPanel);
        logoPanel.setBounds(0, 0, 800, 100);

        topMenuPanel.setLayout(null);

        alumnosTopButton.setText("Alumnos");
        alumnosTopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alumnosTopButtonActionPerformed(evt);
            }
        });
        topMenuPanel.add(alumnosTopButton);
        alumnosTopButton.setBounds(0, 0, 130, 50);

        profesoresTopButton.setText("Profesores");
        profesoresTopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profesoresTopButtonActionPerformed(evt);
            }
        });
        topMenuPanel.add(profesoresTopButton);
        profesoresTopButton.setBounds(133, 0, 130, 50);

        gruposTopButton.setText("Grupos");
        gruposTopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gruposTopButtonActionPerformed(evt);
            }
        });
        topMenuPanel.add(gruposTopButton);
        gruposTopButton.setBounds(266, 0, 130, 50);

        centrosTopButton.setText("Centros");
        centrosTopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                centrosTopButtonActionPerformed(evt);
            }
        });
        topMenuPanel.add(centrosTopButton);
        centrosTopButton.setBounds(400, 0, 130, 50);

        administradoresTopButton.setText("Administradores");
        administradoresTopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                administradoresTopButtonActionPerformed(evt);
            }
        });
        topMenuPanel.add(administradoresTopButton);
        administradoresTopButton.setBounds(533, 0, 130, 50);

        ayudaTopButton.setText("Ayuda");
        ayudaTopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayudaTopButtonActionPerformed(evt);
            }
        });
        topMenuPanel.add(ayudaTopButton);
        ayudaTopButton.setBounds(666, 0, 130, 50);

        getContentPane().add(topMenuPanel);
        topMenuPanel.setBounds(0, 100, 800, 50);
        topMenuPanel.setVisible(false);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 100, 800, 2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void ayudaTopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayudaTopButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ayudaTopButtonActionPerformed

    private void profesoresTopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profesoresTopButtonActionPerformed
        // TODO add your handling code here:
        ProfesoresBuscar pb = new ProfesoresBuscar();
        pb.setLayout(null);
        this.add(pb);
        pb.setBounds(0, 150, 800, 450);
        pb.setPreferredSize(new Dimension(800,450));
        pb.setVisible(true);
    }//GEN-LAST:event_profesoresTopButtonActionPerformed

    private void centrosTopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_centrosTopButtonActionPerformed
        // TODO add your handling code here:
        CentrosBuscar cb = new CentrosBuscar();
        cb.setLayout(null);
        this.add(cb);
        cb.setBounds(0, 150, 800, 450);
        cb.setPreferredSize(new Dimension(800,450));
        cb.setVisible(true);
    }//GEN-LAST:event_centrosTopButtonActionPerformed

    private void gruposTopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gruposTopButtonActionPerformed
        // TODO add your handling code here:
        //profesoresPanel.setVisible(false);
        //com.proyecto1dam.utilidades.Utiles.ocultarPaneles(this);
        
        GruposBuscar gf = new GruposBuscar();
        gf.setLayout(null);
        this.add(gf);
        gf.setBounds(0, 150, 800, 450);
        gf.setPreferredSize(new Dimension(800,450));
        gf.setVisible(true);
       
    }//GEN-LAST:event_gruposTopButtonActionPerformed

    private void alumnosTopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alumnosTopButtonActionPerformed
        // TODO add your handling code here:
        AlumnosBuscar alb = new AlumnosBuscar();
        alb.setLayout(null);
        this.add(alb);
        alb.setBounds(0, 150, 800, 450);
        alb.setPreferredSize(new Dimension(800,450));
        alb.setVisible(true);
    }//GEN-LAST:event_alumnosTopButtonActionPerformed

    private void administradoresTopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_administradoresTopButtonActionPerformed
        // TODO add your handling code here:
        AdministradoresBuscar adb = new AdministradoresBuscar();
        adb.setLayout(null);
        this.add(adb);
        adb.setBounds(0, 150, 800, 450);
        adb.setPreferredSize(new Dimension(800,450));
        adb.setVisible(true);
    }//GEN-LAST:event_administradoresTopButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MarcoBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MarcoBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MarcoBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MarcoBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MarcoBase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton administradoresTopButton;
    private javax.swing.JButton alumnosTopButton;
    private javax.swing.JButton ayudaTopButton;
    private javax.swing.JButton centrosTopButton;
    private javax.swing.JButton gruposTopButton;
    private javax.swing.JLabel identifLabel;
    private javax.swing.JPanel identificarPanel;
    private javax.swing.JLabel imgLabel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel logoIMGPanel;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel nombreESALabel;
    private javax.swing.JPanel nombrePanel;
    private javax.swing.JButton profesoresTopButton;
    private javax.swing.JPanel topMenuPanel;
    private javax.swing.JLabel usuarioLabel;
    // End of variables declaration//GEN-END:variables
}
