/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.proyecto1dam.vista;

/**
 *
 * @author amacias
 */
public class ProfesoresTabla extends javax.swing.JPanel {

    /**
     * Creates new form ProfesoresTabla
     */
    public ProfesoresTabla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        botoneraProfesPanel = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 450));
        setLayout(null);

        menuLabel.setFont(new java.awt.Font("Ubuntu Light", 3, 24)); // NOI18N
        menuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuLabel.setText("PROFESORES");
        add(menuLabel);
        menuLabel.setBounds(0, 0, 800, 50);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1);
        jScrollPane1.setBounds(20, 70, 760, 170);

        botoneraProfesPanel.setLayout(null);

        jButton2.setText("<html><center>Ver<br />Detalles</center></html>");
        botoneraProfesPanel.add(jButton2);
        jButton2.setBounds(0, 0, 90, 90);

        jButton3.setText("<html><center>Modificar<br />Profesor</center></html>");
        botoneraProfesPanel.add(jButton3);
        jButton3.setBounds(90, 0, 90, 90);

        jButton4.setText("<html><center>Borrar<br />Profesor</center></html>");
        botoneraProfesPanel.add(jButton4);
        jButton4.setBounds(180, 0, 90, 90);

        jButton5.setText("Ayuda");
        botoneraProfesPanel.add(jButton5);
        jButton5.setBounds(360, 0, 90, 90);

        jButton6.setText("Salir");
        botoneraProfesPanel.add(jButton6);
        jButton6.setBounds(510, 0, 90, 90);

        jButton7.setText("<html><center>Volver<br />al Menú</center></html>");
        botoneraProfesPanel.add(jButton7);
        jButton7.setBounds(270, 0, 90, 90);

        add(botoneraProfesPanel);
        botoneraProfesPanel.setBounds(100, 325, 600, 90);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botoneraProfesPanel;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel menuLabel;
    // End of variables declaration//GEN-END:variables
}
