/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.proyecto1dam.vista;

import com.proyecto1dam.inicio.*;
import com.sun.awt.AWTUtilities;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;

/**
 *
 * @author andres
 */
public class VentanaInicio extends javax.swing.JFrame {

    double inicioTransp = 60, salto = 1;
    Carga hilo;
    
    /**
     * Creates new form VentanaSwing
     */
    public VentanaInicio() {
        initComponents();
        iniciarVentana();
        //MiCursor();
    }
    
    public void iniciarVentana () {
        setLocationRelativeTo(null);
        hilo = new Carga(getBarraSwingJPB(), 50);
        hilo.start();
        hilo = null;
    }
    
    public void MiCursor () {
        Toolkit tk = Toolkit.getDefaultToolkit();
        Image img = tk.getImage("cursor.gif");
        Point p = new Point (0, 0);
        Cursor cursor = tk.createCustomCursor(img, p, "Cursor");
        
        setCursor(cursor);
        this.setVisible(true);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        imgCaballos = new javax.swing.JLabel();
        barraSwingJPB = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 340));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setMinimumSize(new java.awt.Dimension(400, 340));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 340));

        imgCaballos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/splash_bg.jpg"))); // NOI18N

        barraSwingJPB.setBackground(new java.awt.Color(204, 204, 255));
        barraSwingJPB.setForeground(new java.awt.Color(255, 51, 0));
        barraSwingJPB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                barraSwingJPBStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(imgCaballos)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(barraSwingJPB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(imgCaballos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(barraSwingJPB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void barraSwingJPBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_barraSwingJPBStateChanged
        // TODO add your handling code here:
        if (barraSwingJPB.getValue() == inicioTransp && (100-salto)>0) {
            if (salto != 101) {
                AWTUtilities.setWindowOpacity(this, Float.valueOf((100 - salto) / 100+"f"));
                inicioTransp++;
                salto+=3;
            }
            
        }
        if (barraSwingJPB.getValue() == 100) {
            LoginForm f = new LoginForm();
            f.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_barraSwingJPBStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraSwingJPB;
    private javax.swing.JLabel imgCaballos;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the barraSwingJPB
     */
    public javax.swing.JProgressBar getBarraSwingJPB() {
        return barraSwingJPB;
    }

    /**
     * @param barraSwingJPB the barraSwingJPB to set
     */
    public void setBarraSwingJPB(javax.swing.JProgressBar barraSwingJPB) {
        this.barraSwingJPB = barraSwingJPB;
    }
}
